services:
  product-services:
    build: ./product-services
    ports:
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=${PRODUCT_DB_HOST}
      - DB_NAME=${PRODUCT_DB_NAME}
      - DB_USER=${PRODUCT_DB_USER}
      - DB_PASSWORD=${PRODUCT_DB_PASSWORD}
    container_name: product-services
    restart: always
    depends_on:
      - product-db

  product-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - "3306:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    container_name: product-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: product-db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - product-db
    container_name: phpmyadmin
  
  cart-services:
    build: ./cart-services
    ports:
      - "8000:8000"
    container_name: cart-services
    restart: always
    environment:
        MONGO_URI: "mongodb://mongo-db:27017/cartdb"
    depends_on:
      - mongo-db

  review-services:
      build: ./review-services
      ports:
        - "5002:5002"
      container_name: review-services
      restart: always
      env_file:
        - .env
      depends_on:
        - mongo-db
      environment:
        MONGO_URI: mongodb://mongo-db:27017/reviewdb

  user-services:
    build: ./user-services
    ports:
      - "4000:4000"
    container_name: user-services
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=${USER_DB_HOST}
      - DB_NAME=${USER_DB_NAME}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    container_name: postgres-db
    restart: always

  mongo-db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-db-data:/data/db
    container_name: mongo-db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/?authSource=admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    restart: always
    depends_on:
      - mongo-db

volumes:
    product-db-data: 
    mongo-db-data:
    postgres-db-data: